api_platform:
    title: 'LaNimesAlerie'
    description: 'API alimentant le dashboard du businessCase'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
